rg_project_dirs <- function() {
  c(
    "source",
    "source/protocol",
    "source/sap",
    "source/csr",
    "source/acrf",
    "source/tabulation",
    "source/tabulation/specs",
    "source/tabulation/validation",
    "source/analysis",
    "source/analysis/specs",
    "source/analysis/validation",
    "source/analysis/programs",
    "source/other",
    "templates",
    "templates/word",
    "work",
    "work/extracted",
    "work/drafts",
    "work/evidence",
    "work/qc",
    "output"
  )
}

rg_init_project <- function(path, study_id, guide_types = c("adrg", "csdrg"), overwrite = FALSE) {
  if (missing(path) || missing(study_id)) {
    cli::cli_abort("Both path and study_id are required.")
  }
  guide_types <- unique(match.arg(guide_types, choices = c("adrg", "csdrg"), several.ok = TRUE))
  project_path <- rg_norm_path(path)

  if (fs::dir_exists(project_path) && length(fs::dir_ls(project_path, all = TRUE, fail = FALSE)) > 0 && !overwrite) {
    existing_config <- fs::path(project_path, "config.yml")
    if (fs::file_exists(existing_config)) {
      stop("Project already appears to exist. Use overwrite = TRUE to replace config.yml.", call. = FALSE)
    }
  }

  fs::dir_create(project_path)
  purrr::walk(fs::path(project_path, rg_project_dirs()), fs::dir_create)

  cfg <- rg_default_config(
    study_id = study_id,
    project_id = fs::path_file(project_path),
    guide_types = guide_types
  )
  rg_write_config(cfg, fs::path(project_path, "config.yml"), overwrite = overwrite)
  rg_write_default_render_assets(project_path)
  invisible(project_path)
}

rg_default_rmd_template <- function() {
  c(
    "---",
    "title: \"Reviewer Guide\"",
    "doc_type: \"reviewers_guide\"",
    "version: \"0.3\"",
    "status: \"draft\"",
    "output:",
    "  officedown::rdocx_document:",
    "    reference_docx: \"word/base.docx\"",
    "    toc: true",
    "    number_sections: false",
    "    tables:",
    "      layout: fixed",
    "      width: 1.0",
    "      caption:",
    "        pre: \"Table \"",
    "        sep: \": \"",
    "    plots:",
    "      align: center",
    "      caption:",
    "        pre: \"Figure \"",
    "        sep: \": \"",
    "---",
    "",
    "```{r setup, include=FALSE}",
    "knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)",
    "ctx <- rg_render_context",
    "rg_scalar <- function(x, default = \"\") {",
    "  if (is.null(x) || length(x) == 0 || is.na(x[[1]])) default else as.character(x[[1]])",
    "}",
    "rg_emit_table <- function(x) {",
    "  flextable::flextable_to_rmd(rg_flextable(x))",
    "  cat(\"\\n\\n\")",
    "}",
    "```",
    "",
    "# `r ctx$title`",
    "",
    "Study: `r rg_scalar(ctx$study_id, \"NA\")`",
    "",
    "Generated by reviewerguideR officedown harness on `r ctx$generated_on`",
    "",
    "```{r sections, results='asis'}",
    "for (section in ctx$draft$sections) {",
    "  cat(\"\\n## \", rg_scalar(section$section_title, \"Untitled Section\"), \"\\n\\n\", sep = \"\")",
    "  text <- rg_scalar(section$draft_markdown)",
    "  if (!nzchar(trimws(text))) {",
    "    text <- \"No draft text was generated.\"",
    "  }",
    "  cat(text, \"\\n\\n\", sep = \"\")",
    "",
    "  section_id <- rg_scalar(section$section_id)",
    "  if (grepl(\"dataset_inventory$\", section_id)) {",
    "    tbl <- rg_compact_table(",
    "      ctx$data$define_datasets,",
    "      c(\"dataset_name\", \"dataset_label\", \"structure\", \"purpose\", \"class\")",
    "    )",
    "    rg_emit_table(tbl)",
    "  }",
    "  if (grepl(\"conformance_findings$\", section_id)) {",
    "    tbl <- rg_compact_table(",
    "      ctx$data$validation_findings,",
    "      c(\"rule_id\", \"severity\", \"dataset_name\", \"variable_name\", \"message\", \"count\", \"status\")",
    "    )",
    "    rg_emit_table(tbl)",
    "  }",
    "}",
    "```",
    "",
    "```{r valuelevel, results='asis'}",
    "if (nrow(ctx$data$define_valuelevel) > 0) {",
    "  cat(\"\\n## Value-Level Metadata\\n\\n\")",
    "  valuelevel_tbl <- rg_compact_table(",
    "    ctx$data$define_valuelevel,",
    "    c(",
    "      \"value_list_oid\", \"where_clause_oid\", \"dataset_name\", \"variable_name\",",
    "      \"where_variable_name\", \"comparator\", \"check_value\", \"mandatory\"",
    "    )",
    "  )",
    "  rg_emit_table(valuelevel_tbl)",
    "}",
    "```",
    "",
    "```{r qc-summary, results='asis'}",
    "if (nrow(ctx$qc_summary) > 0) {",
    "  cat(\"\\n## QC Summary\\n\\n\")",
    "  qc_tbl <- rg_compact_table(",
    "    ctx$qc_summary,",
    "    c(",
    "      \"guide_type\", \"summary_status\", \"total_rows\", \"fail_rows\",",
    "      \"warning_fail_rows\", \"error_fail_rows\", \"review_required_rows\",",
    "      \"manifest_drift_rows\"",
    "    )",
    "  )",
    "  rg_emit_table(qc_tbl)",
    "}",
    "```",
    ""
  )
}

rg_write_default_rmd_template <- function(path, overwrite = FALSE) {
  if (fs::file_exists(path) && !overwrite) {
    return(invisible(path))
  }
  fs::dir_create(fs::path_dir(path))
  writeLines(rg_default_rmd_template(), path, useBytes = TRUE)
  invisible(path)
}

rg_write_default_reference_docx <- function(path, overwrite = FALSE) {
  if (fs::file_exists(path) && !overwrite) {
    return(invisible(path))
  }
  fs::dir_create(fs::path_dir(path))
  doc <- officer::read_docx()
  doc <- officer::body_add_par(doc, "Reviewer Guide Style Base", style = "heading 1")
  doc <- officer::body_add_par(
    doc,
    "Replace this file with the study or company Word style base. Body content is not imported.",
    style = "Normal"
  )
  print(doc, target = path)
  invisible(path)
}

rg_write_default_render_assets <- function(project_path) {
  rg_write_default_rmd_template(fs::path(project_path, "templates", "reviewers-guide.Rmd"))
  rg_write_default_reference_docx(fs::path(project_path, "templates", "word", "base.docx"))
  invisible(project_path)
}
